global using LocalBusinessDirectory.Data.Businesses;
global using LocalBusinessDirectory.Data.Categories;
global using LocalBusinessDirectory.Data.Helpers;
global using LocalBusinessDirectory.Data.Models;
global using LocalBusinessDirectory.Data.Offers;
global using LocalBusinessDirectory.Data.Ratings;
global using LocalBusinessDirectory.Data.Sql;
global using LocalBusinessDirectory.Data.Users;
global using LocalBusinessDirectory.Validation;